# Generated by Django 5.1.7 on 2025-10-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ichimliklar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichimliklar',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ichimliklar',
            name='narxi',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
