# Generated by Django 5.1.7 on 2025-10-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ichimliklar_image_alter_ichimliklar_narxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichimliklar',
            name='chegirma',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ichimliklar',
            name='chegirma_miqdori',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
