# Generated by Django 5.1.7 on 2025-10-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ichimliklar_chegirma_ichimliklar_chegirma_miqdori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kompaniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('manzili', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='ichimliklar',
            name='kompaniya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kompaniya'),
        ),
    ]
