# Generated by Django 5.1.7 on 2025-10-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_kompaniya_ichimliklar_kompaniya'),
    ]

    operations = [
        migrations.AddField(
            model_name='kompaniya',
            name='tavsif',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
