# Generated by Django 5.1.7 on 2025-10-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_kompaniya_tavsif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kompaniya',
            name='manzili',
        ),
        migrations.AddField(
            model_name='kompaniya',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='kompaniyalar/'),
        ),
        migrations.AddField(
            model_name='kompaniya',
            name='mamlakat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kompaniya',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='kompaniya',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kompaniya',
            name='nomi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kompaniya',
            name='tavsif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kompaniya',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
