# Generated by Django 5.1.7 on 2025-10-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_kompaniya_manzili_kompaniya_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ichimliklar',
            name='chegirma',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ichimliklar',
            name='chegirma_miqdori',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ichimliklar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ichimliklar',
            name='kompaniya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ichimliklar', to='app.kompaniya'),
        ),
        migrations.AlterField(
            model_name='ichimliklar',
            name='miqdori',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kompaniya',
            name='mamlakat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kompaniya',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
