# Generated by Django 5.1.7 on 2025-10-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_ichimliklar_chegirma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompaniya',
            name='mamlakat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kompaniya',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
